protocols = imap lmtp
listen = *

ssl = required
ssl_cert = </etc/postfix/certs/mail.cargo-port.eu.crt
ssl_key = </etc/postfix/certs/mail.cargo-port.eu.key

mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir
mail_uid = dovecot
mail_gid = mail

userdb {
  driver = passwd-file
  args = /etc/dovecot/users
}

passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}
